export const dataPortfolio = [
  {
    img: "https://themetechmount.com/html/dezily/images/portfolio/portfolio-04.jpg",
    title: "Project Details",
    descriptionOne:"We are seamlessly merge two key components – friendly nature and latest technology machine. We are uniquely deploy cross-team benefits with wireless testing procedures.",
    descriptionTwo:"Cardiologists are doctors who specialize in diagnosing and treating diseases or conditions of the heart and blood cardiovascular.",
    location: "New York United States",
    clients: "Envato Group, US",
    category: "Doctors",
    projectHead: "Mr. John Meckency",
  },
  {
    img: "https://themetechmount.com/html/dezily/images/portfolio/portfolio-04.jpg",
    title: "Project Details",
    descriptionOne:"We are seamlessly merge two key components – friendly nature and latest technology machine. We are uniquely deploy cross-team benefits with wireless testing procedures.",
    descriptionTwo:"Cardiologists are doctors who specialize in diagnosing and treating diseases or conditions of the heart and blood cardiovascular.",
    location: "New York United States",
    clients: "Envato Group, US",
    category: "Doctors",
    projectHead: "Mr. John Meckency",
  },
  {
    img: "https://themetechmount.com/html/dezily/images/portfolio/portfolio-04.jpg",
    title: "Project Details",
    descriptionOne:"We are seamlessly merge two key components – friendly nature and latest technology machine. We are uniquely deploy cross-team benefits with wireless testing procedures.",
    descriptionTwo:"Cardiologists are doctors who specialize in diagnosing and treating diseases or conditions of the heart and blood cardiovascular.",
    location: "New York United States",
    clients: "Envato Group, US",
    category: "Doctors",
    projectHead: "Mr. John Meckency",
  },
  {
    img: "https://themetechmount.com/html/dezily/images/portfolio/portfolio-04.jpg",
    title: "Project Details",
    descriptionOne:"We are seamlessly merge two key components – friendly nature and latest technology machine. We are uniquely deploy cross-team benefits with wireless testing procedures.",
    descriptionTwo:"Cardiologists are doctors who specialize in diagnosing and treating diseases or conditions of the heart and blood cardiovascular.",
    location: "New York United States",
    clients: "Envato Group, US",
    category: "Doctors",
    projectHead: "Mr. John Meckency",
  },
  {
    img: "https://themetechmount.com/html/dezily/images/portfolio/portfolio-04.jpg",
    title: "Project Details",
    descriptionOne:"We are seamlessly merge two key components – friendly nature and latest technology machine. We are uniquely deploy cross-team benefits with wireless testing procedures.",
    descriptionTwo:"Cardiologists are doctors who specialize in diagnosing and treating diseases or conditions of the heart and blood cardiovascular.",
    location: "New York United States",
    clients: "Envato Group, US",
    category: "Doctors",
    projectHead: "Mr. John Meckency",
  },
];